

services:
  # The Redis service for our job queue
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # [NEW] The PostgreSQL database service
  postgres:
    image: "postgres:15-alpine"
    ports:
      - "5432:5432" # Expose the port for potential local connections
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=distributed_compute

  # The Scheduler service, which will run our Python code
  scheduler:
    build: ./scheduler
    ports:
      - "8000:8000"
    volumes:
      - ./scheduler:/app
    depends_on:
      - redis
      - postgres # [UPDATED] Ensures Postgres starts before the scheduler

volumes:
  redis_data:
  postgres_data: # [NEW] Define a persistent volume for Postgres data