# docker-compose.yml

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: "postgres:15-alpine"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=distributed_compute

  scheduler:
    build: ./scheduler
    ports:
      - "8000:8000"
      
    volumes:
      - ./scheduler:/app
    depends_on:
      - redis
      - postgres

  # [NEW] The Prometheus service
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090" # Web UI for Prometheus
    volumes:
      - ./prometheus:/etc/prometheus/ # Mount our config file
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - scheduler

  # [NEW] The Grafana service
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000" # Web UI for Grafana
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  redis_data:
  postgres_data:
  grafana_data: